name: All Tests
on: [push, pull_request]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Run Backend Tests
        working-directory: ./financial-tracker-backend
        run: ./mvnw test

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Frontend dependencies
        working-directory: ./financial-tracker-frontend
        run: npm ci
        
      - name: Run Frontend tests
        working-directory: ./financial-tracker-frontend
        run: npm test -- --watchAll=false --passWithNoTests
        
      - name: Build Frontend
        working-directory: ./financial-tracker-frontend
        run: npm run build

  etl-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install ETL dependencies
        working-directory: ./financial-tracker-etl
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run ETL tests
        working-directory: ./financial-tracker-etl
        run: |
          python -m pytest tests/ -v --cov=etl --cov-report=xml --cov-report=html

  coverage-report:
    needs: [backend-tests, frontend-tests, etl-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Upload Backend Coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./financial-tracker-backend/target/site/jacoco
          fail_ci_if_error: false
          
      - name: Upload Frontend Coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./financial-tracker-frontend/coverage
          fail_ci_if_error: false
          
      - name: Upload ETL Coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./financial-tracker-etl/htmlcov
          fail_ci_if_error: false 